version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-upload:
    executor:
      name: android/android-machine
    environment:
      release_notes: "Release notes for this build"
      git_release_notes: false
      git_commit_id: false
      notify: true
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - run:
          name: Assemble debug build
          command: ./gradlew assembleDebug
      - run:
          name: Run Unit Test
          command: ./gradlew test
      - run:
          name: Upload to TestApp.io
          command: |
            export INSTALL_DIR=/tmp
            curl -Ls https://github.com/testappio/cli/releases/latest/download/install | bash
            $INSTALL_DIR/ta-cli publish --api_token=$TESTAPPIO_API_TOKEN --app_id=$TESTAPPIO_APP_ID --release="android" --apk=./app/build/outputs/apk/debug/app-debug.apk --release_notes=$release_notes --notify=$notify --git_release_notes=$git_release_notes --git_commit_id=$git_commit_id --source="Circle CI"

workflows:
  testappio-release:
    jobs:
      - build-and-upload