version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-upload:
    executor:
      name: android/android-machine
    environment:
      release_notes: "Release notes for this build"
      notify: true
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version
      - run:
          name: Install OpenJDK 17
          command: ./gradlew assembleDebug

workflows:
  testappio-release:
    jobs:
      - build-and-upload